# Generated by Django 3.1 on 2023-01-28 12:38

from django.db import migrations, models
import garpix_page.utils.all_sites
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_menu', '0003_auto_20220303_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sites',
            field=models.ManyToManyField(default=garpix_page.utils.all_sites.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
