# Generated by Django 3.1 on 2023-07-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_order', '0001_initial'),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('basepayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.basepayment')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
            bases=('garpix_order.basepayment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.baseorder')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
            },
            bases=('garpix_order.baseorder',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('baseorderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.baseorderitem')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('garpix_order.baseorderitem',),
        ),
    ]
