# Generated by Django 3.1 on 2023-07-21 08:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0002_auto_20230721_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recurring',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='last_payment_at',
        ),
        migrations.AddField(
            model_name='baseorder',
            name='next_payment_date',
            field=models.DateTimeField(null=True, verbose_name='Дата слелующего платежа'),
        ),
        migrations.AddField(
            model_name='recurring',
            name='payment_system',
            field=models.CharField(choices=[('ROBOKASSA', 'Робокасса')], default='ROBOKASSA', max_length=9, verbose_name='Система оплаты'),
        ),
    ]
