# Generated by Django 3.1 on 2024-05-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0003_auto_20230721_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseorder',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_order.recurring', verbose_name='Рекуррент'),
        ),
    ]
