name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.8


            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip3 install cookiecutter
                pip3 install pipenv

            - name: Create venv
              run: |
                pipenv install
                pipenv shell

            - name: Create env
              run: |
                echo "${{ secrets.env }}" > .env

            - name: Build binary wheel and a source tarball
              run: python3 backend/manage.py startpackage garpix_order && SECRET_KEY=${{ secrets.test_pypi }} python backend/manage.py pack garpix_order

#            - name: Publish distribution to PyPI
#              uses: pypa/gh-action-pypi-publish@master
#              with:
#                password: ${{ secrets.test_pypi }}
#                repository_url: https://upload.test.pypi.org/legacy/
