name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

#            - name: Install dependencies
#              run: |
#                python -m pip install --upgrade pip
#                pip install django djangorestframework django-fsm
          
            - name: Build binary wheel and a source tarball
              run: python backend/garpix_order/setup.py sdist

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: ${{ secrets.test_pypi }}
                repository_url: https://upload.test.pypi.org/legacy/
